/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as NewRouteImport } from './routes/new'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as GoRouteImport } from './routes/go'
import { Route as GiveRouteImport } from './routes/give'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/feedback': typeof FeedbackRoute
  '/give': typeof GiveRoute
  '/go': typeof GoRoute
  '/kids': typeof KidsRoute
  '/new': typeof NewRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/feedback': typeof FeedbackRoute
  '/give': typeof GiveRoute
  '/go': typeof GoRoute
  '/kids': typeof KidsRoute
  '/new': typeof NewRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/feedback': typeof FeedbackRoute
  '/give': typeof GiveRoute
  '/go': typeof GoRoute
  '/kids': typeof KidsRoute
  '/new': typeof NewRoute
  '/today': typeof TodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/feedback'
    | '/give'
    | '/go'
    | '/kids'
    | '/new'
    | '/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/feedback'
    | '/give'
    | '/go'
    | '/kids'
    | '/new'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/feedback'
    | '/give'
    | '/go'
    | '/kids'
    | '/new'
    | '/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  FeedbackRoute: typeof FeedbackRoute
  GiveRoute: typeof GiveRoute
  GoRoute: typeof GoRoute
  KidsRoute: typeof KidsRoute
  NewRoute: typeof NewRoute
  TodayRoute: typeof TodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  FeedbackRoute: FeedbackRoute,
  GiveRoute: GiveRoute,
  GoRoute: GoRoute,
  KidsRoute: KidsRoute,
  NewRoute: NewRoute,
  TodayRoute: TodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
